
#field separator
field_separator: ","

#line separator
line_separator: "\n"

#escaped separator
escape_separator: "\\"

#enclose separator
enclose_separator: "\""

#batch to write and flush
batch_size: 1000000

#data file count
file_count: 1

